name: Terraform Azure Deployment

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI

env:
  ARM_CLIENT_ID: ${{ secrets.APPID_GITHUBDEPLOYER }}
  ARM_TENANT_ID: ${{ secrets.TENANTID_GITHUBDEPLOYER }}
  ARM_CLIENT_SECRET: ${{ secrets.SECRET_GITHUBDEPLOYER }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBID }}
  auth-type: service-principle

jobs:
  terraform_deploy:
    runs-on: windows-latest
    permissions:
        id-token: write
        contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Azure Login
      uses: azure/login@v2 # Action to log in to Azure using the Service Principal
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3 # Action to set up Terraform CLI
      with:
        terraform_version: 1.8.0 # Specify a compatible Terraform version

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        # Pass the sensitive password as an environment variable for Terraform
        # This is picked up by Terraform as TF_VAR_<variable_name>
        TF_VAR_postgresql_admin_password: ${{ secrets.TF_VAR_postgresql_admin_password }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      env:
        TF_VAR_postgresql_admin_password: ${{ secrets.TF_VAR_postgresql_admin_password }}
      # Save the plan output to an artifact for review (optional but good practice)
      # You might want to remove this for production if you use a separate approval step
      # or if the plan output contains sensitive information.
    - name: Upload Terraform Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: terraform.tfplan # Or the path to your plan file if you save it

    - name: Terraform Apply
      id: apply
      # Only run apply if the plan step was successful
      # For production, you might want a manual approval step here.
      run: terraform apply -auto-approve
      env:
        TF_VAR_postgresql_admin_password: ${{ secrets.TF_VAR_postgresql_admin_password }}
